{{- if .Values.machineset.enabled }}
---
# https://docs.openshift.com/container-platform/4.11/machine_management/creating_machinesets/creating-machineset-aws.html
apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  labels:
    machine.openshift.io/cluster-api-cluster: {{ .Values.machineset.cluster_id }}
  name: {{ .Values.machineset.cluster_id }}-infra-{{ .Values.machineset.availability_zone }}
  namespace: openshift-machine-api
spec:
  replicas: 1
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: {{ .Values.machineset.cluster_id }} 
      machine.openshift.io/cluster-api-machineset: {{ .Values.machineset.cluster_id }}-infra-{{ .Values.machineset.availability_zone }}
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: {{ .Values.machineset.cluster_id }} 
        machine.openshift.io/cluster-api-machine-role: infra 
        machine.openshift.io/cluster-api-machine-type: infra 
        machine.openshift.io/cluster-api-machineset: {{ .Values.machineset.cluster_id }}-infra-{{ .Values.machineset.availability_zone }}
    spec:
      metadata:
        labels:
          node-role.kubernetes.io/infra: ""
          node-role.kubernetes.io: infra
      taints:
      - effect: NoSchedule
        key: node-role.kubernetes.io/infra
        value: reserved
      - effect: NoExecute
        key: node-role.kubernetes.io/infra
        value: reserved
      providerSpec:
        value:
          ami:
            id: ami-0993bc7222e12bd80
          apiVersion: awsproviderconfig.openshift.io/v1beta1
          blockDevices:
            - ebs:
                iops: 0
                volumeSize: 120
                volumeType: gp2
          credentialsSecret:
            name: aws-cloud-credentials
          instanceType: m6i.xlarge
          deviceIndex: 0
          iamInstanceProfile:
            id: {{ .Values.machineset.cluster_id }}-worker-profile 
          kind: AWSMachineProviderConfig
          placement:
            availabilityZone: {{ .Values.machineset.availability_zone }}
            availability_zone:  {{ .Values.machineset.region }}
          securityGroups:
            - filters:
                - name: tag:Name
                  values:
                    - {{ .Values.machineset.cluster_id }}-worker-sg 
          subnet:
            filters:
              - name: tag:Name
                values:
                  - {{ .Values.machineset.cluster_id }}-private-{{ .Values.machineset.availability_zone }} 
          tags:
            - name: kubernetes.io/cluster/{{ .Values.machineset.cluster_id }} 
              value: owned
          userDataSecret:
            name: worker-user-data
{{- end }}