---
apiVersion: loki.grafana.com/v1
kind: LokiStack
metadata:
  name: {{ .Values.logging.loki_name }} 
  namespace: {{ .Values.logging.namespace }}
spec:
  size: 1x.extra-small
  storage:
    secret:
      name: logging-loki-s3
      type: s3
  storageClassName: {{ .Values.logging.storageclass }}
  tenants:
    mode: {{ .Values.logging.namespace }}