apiVersion: observability.openshift.io/v1alpha1
kind: UIPlugin
metadata:
  name: logging
spec:
  type: Logging
  logging:
    lokiStack:
      name: {{ .Values.logging.loki_name }}
    logsLimit: 50
    timeout: 30s