{{- if .Values.crw }}
apiVersion: org.eclipse.che/v2
kind: CheCluster
metadata:
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "25"
  name: {{ .Values.crw.name | default "codeready-workspaces" | quote }}
  namespace: {{ .Values.crw.namespace | default "tl500-workspaces" | quote }}
spec:
  components:
    database:
      externalDb: false
    metrics:
      enable: false
    cheServer:
      debug: false
      logLevel: INFO
      extraProperties: {{ toYaml .Values.crw.properties | nindent 8 | default "" }}
  devEnvironments:
    secondsOfRunBeforeIdling: -1
    defaultNamespace:
      template: <username>-devspaces
    secondsOfInactivityBeforeIdling: -1
    storage:
      pvcStrategy: per-user
{{- end }}
