{{- if .Values.gitlab -}}
{{ $root_pass := include "gitlab.root_password" . }}
{{ $db_user := include "gitlab.postgres.user" . }}
{{ $db_pass := include "gitlab.postgres.password" . }}
{{ $db_admin_pass := include "gitlab.postgres.admin_password" . }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.gitlab.app_name }}-credentials"
  namespace: "{{ .Values.gitlab.namespace }}"
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  root_password: {{ $root_pass | b64enc | quote }}
  postgres_user: {{ $db_user | b64enc | quote }}
  postgres_password: {{ $db_pass | b64enc | quote }}
  postgres_admin_password: {{ $db_admin_pass | b64enc | quote }}
immutable: true
{{- if .Values.gitlab.cacert }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.gitlab.app_name }}-ca"
  namespace: "{{ .Values.gitlab.namespace }}"
type: Opaque
data:
  ca-cert.crt: "{{ .Values.gitlab.cacert }}"
{{- end }}
{{- end }}